// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9UhkcIAJJMXEJ8-M8qKu8gCCoL7kpKt0',
    appId: '1:1064917493526:web:d48109379a64aad6929237',
    messagingSenderId: '1064917493526',
    projectId: 'kitajomdemo',
    authDomain: 'kitajomdemo.firebaseapp.com',
    storageBucket: 'kitajomdemo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC50PYrp-1seZPOEBcPisYPmDNNsM7YbKk',
    appId: '1:1064917493526:android:e1cc6af2113b6dbb929237',
    messagingSenderId: '1064917493526',
    projectId: 'kitajomdemo',
    storageBucket: 'kitajomdemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMQIMvE4t7B6UcoJaBJmkFmNcQNCUt6jE',
    appId: '1:1064917493526:ios:eccbea353e2977c5929237',
    messagingSenderId: '1064917493526',
    projectId: 'kitajomdemo',
    storageBucket: 'kitajomdemo.appspot.com',
    iosBundleId: 'com.example.kitajom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMQIMvE4t7B6UcoJaBJmkFmNcQNCUt6jE',
    appId: '1:1064917493526:ios:1656806a92eeb326929237',
    messagingSenderId: '1064917493526',
    projectId: 'kitajomdemo',
    storageBucket: 'kitajomdemo.appspot.com',
    iosBundleId: 'com.example.kitajom.RunnerTests',
  );
}
